# Generated by Django 2.1.7 on 2020-08-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MntClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('class_subtype', models.CharField(blank=True, max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=45, null=True)),
                ('explanation', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'mnt_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MntProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'mnt_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MntVardata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('sales_units', models.IntegerField(blank=True, null=True)),
                ('price_rur', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mnt_vardata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('class_subtype', models.CharField(blank=True, max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'nb_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('cluster', models.CharField(blank=True, max_length=45, null=True)),
                ('target_market', models.CharField(blank=True, max_length=10, null=True)),
                ('cpu_vendor', models.CharField(blank=True, max_length=45, null=True)),
                ('base_platform', models.CharField(blank=True, max_length=45, null=True)),
                ('gpu_list', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_resulution_list', models.CharField(blank=True, max_length=45, null=True)),
                ('touchscreen', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'nb_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbVardata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('sales_units', models.IntegerField(blank=True, null=True)),
                ('price_rur', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nb_vardata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MntProductsHasMntClasses',
            fields=[
                ('fk_products', models.ForeignKey(db_column='fk_products', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marketability.MntProducts')),
            ],
            options={
                'db_table': 'mnt_products_has_mnt_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbProductsHasNbClasses',
            fields=[
                ('fk_products', models.ForeignKey(db_column='fk_products', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='marketability.NbProducts')),
            ],
            options={
                'db_table': 'nb_products_has_nb_classes',
                'managed': False,
            },
        ),
    ]
