# Generated by Django 3.1.2 on 2021-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketability', '0003_txthow_txtratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('class_subtype', models.CharField(blank=True, max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ups_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('appear_month', models.DateField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=45, null=True)),
                ('type_line', models.CharField(blank=True, max_length=45, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=45, null=True)),
                ('level', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ups_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsProductsHasUpsClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ups_products_has_ups_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsShopsPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('modfication_href', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_price', models.FloatField()),
                ('modification_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ups_shops_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsVardata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.DateField(blank=True, null=True)),
                ('sales_units', models.IntegerField(blank=True, null=True)),
                ('price_rur', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ups_vardata',
                'managed': False,
            },
        ),
    ]
